- name: install apach2
  apt: name=apache2 state=present
  become: yes

- name: register apache2 service and start
  #shell: systemctl start apache2
  service: name=apache2 state=started enabled=yes
  become: yes
